import { create } from "zustand"
import type { Job, Candidate, Interview, Activity, JobStatus, CandidateStatus } from "@/types"

interface AppState {
  jobs: Job[]
  candidates: Candidate[]
  interviews: Interview[]
  activities: Activity[]
  addJob: (job: Omit<Job, "id" | "createdAt" | "applicants">) => void
  updateJobStatus: (id: string, status: JobStatus) => void
  addCandidate: (candidate: Omit<Candidate, "id" | "appliedAt" | "stage">) => void
  updateCandidateStatus: (id: string, status: CandidateStatus) => void
}

const sampleJobs: Job[] = [
  {
    id: "j1",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    type: "full-time",
    salaryMin: 150000,
    salaryMax: 200000,
    description: "We are looking for a senior frontend engineer to lead our React-based dashboard.",
    status: "Active",
    applicants: 24,
    createdAt: new Date("2026-06-01"),
  },
  {
    id: "j2",
    title: "Product Manager",
    department: "Product",
    location: "New York, NY",
    type: "full-time",
    salaryMin: 130000,
    salaryMax: 175000,
    description: "Lead product strategy for our AI-powered recruitment platform.",
    status: "Active",
    applicants: 18,
    createdAt: new Date("2026-06-05"),
  },
  {
    id: "j3",
    title: "ML Engineer",
    department: "Engineering",
    location: "Remote",
    type: "full-time",
    salaryMin: 160000,
    salaryMax: 220000,
    description: "Build and optimize our AI screening models.",
    status: "Active",
    applicants: 31,
    createdAt: new Date("2026-05-20"),
  },
  {
    id: "j4",
    title: "UX Designer",
    department: "Design",
    location: "Austin, TX",
    type: "full-time",
    salaryMin: 100000,
    salaryMax: 140000,
    description: "Design intuitive interfaces for enterprise recruitment workflows.",
    status: "Paused",
    applicants: 12,
    createdAt: new Date("2026-05-15"),
  },
  {
    id: "j5",
    title: "DevOps Engineer",
    department: "Engineering",
    location: "Seattle, WA",
    type: "full-time",
    salaryMin: 140000,
    salaryMax: 185000,
    description: "Manage and scale our cloud infrastructure on AWS.",
    status: "Active",
    applicants: 9,
    createdAt: new Date("2026-06-10"),
  },
  {
    id: "j6",
    title: "Data Analyst Intern",
    department: "Data",
    location: "Remote",
    type: "internship",
    salaryMin: 30000,
    salaryMax: 45000,
    description: "Assist the data team with analysis and reporting.",
    status: "Draft",
    applicants: 0,
    createdAt: new Date("2026-07-01"),
  },
  {
    id: "j7",
    title: "Backend Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    type: "full-time",
    salaryMin: 145000,
    salaryMax: 195000,
    description: "Design and build scalable microservices.",
    status: "Closed",
    applicants: 42,
    createdAt: new Date("2026-04-01"),
  },
  {
    id: "j8",
    title: "Technical Writer",
    department: "Marketing",
    location: "Remote",
    type: "contract",
    salaryMin: 80000,
    salaryMax: 110000,
    description: "Create comprehensive API documentation and user guides.",
    status: "Active",
    applicants: 7,
    createdAt: new Date("2026-06-20"),
  },
]

const sampleCandidates: Candidate[] = [
  {
    id: "c1",
    name: "Emily Chen",
    email: "emily.chen@email.com",
    phone: "+1 555-0101",
    jobId: "j1",
    jobTitle: "Senior Frontend Engineer",
    experience: 8,
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind CSS"],
    aiScore: 92,
    rating: 5,
    status: "Interview",
    stage: "Interview",
    notes: "Strong candidate with extensive React experience. Led migration from Vue to React at previous company.",
    appliedAt: new Date("2026-06-10"),
  },
  {
    id: "c2",
    name: "Marcus Johnson",
    email: "marcus.j@email.com",
    phone: "+1 555-0102",
    jobId: "j1",
    jobTitle: "Senior Frontend Engineer",
    experience: 5,
    skills: ["React", "JavaScript", "CSS", "Redux", "Jest"],
    aiScore: 78,
    rating: 4,
    status: "Screening",
    stage: "Screening",
    notes: "Good technical skills. Needs to demonstrate leadership experience.",
    appliedAt: new Date("2026-06-12"),
  },
  {
    id: "c3",
    name: "Sarah Kim",
    email: "sarah.kim@email.com",
    phone: "+1 555-0103",
    jobId: "j2",
    jobTitle: "Product Manager",
    experience: 10,
    skills: ["Product Strategy", "Agile", "Jira", "Data Analysis", "Stakeholder Management"],
    aiScore: 88,
    rating: 5,
    status: "Offer",
    stage: "Offer",
    notes: "Exceptional product sense. Previously PM at a Series C startup.",
    appliedAt: new Date("2026-05-28"),
  },
  {
    id: "c4",
    name: "David Park",
    email: "david.park@email.com",
    phone: "+1 555-0104",
    jobId: "j3",
    jobTitle: "ML Engineer",
    experience: 6,
    skills: ["Python", "TensorFlow", "PyTorch", "NLP", "MLOps"],
    aiScore: 95,
    rating: 5,
    status: "Interview",
    stage: "Interview",
    notes: "Published researcher in NLP. Strong coding skills and system design thinking.",
    appliedAt: new Date("2026-06-01"),
  },
  {
    id: "c5",
    name: "Lisa Wang",
    email: "lisa.wang@email.com",
    phone: "+1 555-0105",
    jobId: "j4",
    jobTitle: "UX Designer",
    experience: 7,
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Accessibility"],
    aiScore: 85,
    rating: 4,
    status: "Applied",
    stage: "Applied",
    notes: "Impressive portfolio with enterprise SaaS experience.",
    appliedAt: new Date("2026-06-15"),
  },
  {
    id: "c6",
    name: "James O'Brien",
    email: "james.ob@email.com",
    phone: "+1 555-0106",
    jobId: "j5",
    jobTitle: "DevOps Engineer",
    experience: 4,
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    aiScore: 72,
    rating: 3,
    status: "Screening",
    stage: "Screening",
    notes: "Solid infrastructure skills. AWS certified.",
    appliedAt: new Date("2026-06-18"),
  },
  {
    id: "c7",
    name: "Priya Patel",
    email: "priya.p@email.com",
    phone: "+1 555-0107",
    jobId: "j3",
    jobTitle: "ML Engineer",
    experience: 3,
    skills: ["Python", "Scikit-learn", "Pandas", "SQL", "Computer Vision"],
    aiScore: 68,
    rating: 3,
    status: "Rejected",
    stage: "Rejected",
    notes: "Good fundamentals but lacks experience with large-scale ML systems.",
    appliedAt: new Date("2026-06-05"),
  },
  {
    id: "c8",
    name: "Alex Rivera",
    email: "alex.r@email.com",
    phone: "+1 555-0108",
    jobId: "j7",
    jobTitle: "Backend Engineer",
    experience: 9,
    skills: ["Go", "Rust", "PostgreSQL", "Redis", "Microservices"],
    aiScore: 91,
    rating: 5,
    status: "Hired",
    stage: "Hired",
    notes: "Started on July 1st. Excellent system design skills.",
    appliedAt: new Date("2026-04-15"),
  },
  {
    id: "c9",
    name: "Nina Zhao",
    email: "nina.zhao@email.com",
    phone: "+1 555-0109",
    jobId: "j2",
    jobTitle: "Product Manager",
    experience: 4,
    skills: ["User Research", "Analytics", "Roadmapping", "A/B Testing", "SQL"],
    aiScore: 74,
    rating: 3,
    status: "Applied",
    stage: "Applied",
    notes: "Transitioning from data analytics to product. Strong analytical background.",
    appliedAt: new Date("2026-06-25"),
  },
  {
    id: "c10",
    name: "Tom Bradley",
    email: "tom.b@email.com",
    phone: "+1 555-0110",
    jobId: "j1",
    jobTitle: "Senior Frontend Engineer",
    experience: 12,
    skills: ["React", "Vue", "Angular", "TypeScript", "Web Performance"],
    aiScore: 89,
    rating: 4,
    status: "Interview",
    stage: "Interview",
    notes: "Very experienced. Concerned about cultural fit — prefers smaller teams.",
    appliedAt: new Date("2026-06-08"),
  },
  {
    id: "c11",
    name: "Aisha Mohammed",
    email: "aisha.m@email.com",
    phone: "+1 555-0111",
    jobId: "j8",
    jobTitle: "Technical Writer",
    experience: 5,
    skills: ["Technical Writing", "API Docs", "Markdown", "OpenAPI", "Git"],
    aiScore: 82,
    rating: 4,
    status: "Screening",
    stage: "Screening",
    notes: "Excellent writing samples. Previously documented a public API with 10K+ developers.",
    appliedAt: new Date("2026-06-22"),
  },
  {
    id: "c12",
    name: "Carlos Mendez",
    email: "carlos.m@email.com",
    phone: "+1 555-0112",
    jobId: "j5",
    jobTitle: "DevOps Engineer",
    experience: 6,
    skills: ["AWS", "GCP", "Docker", "Python", "Monitoring"],
    aiScore: 80,
    rating: 4,
    status: "Applied",
    stage: "Applied",
    notes: "Multi-cloud experience. Strong monitoring and observability skills.",
    appliedAt: new Date("2026-07-02"),
  },
]

const sampleInterviews: Interview[] = [
  { id: "i1", candidateId: "c1", candidateName: "Emily Chen", jobId: "j1", jobTitle: "Senior Frontend Engineer", scheduledAt: new Date("2026-07-15T10:00:00"), date: new Date("2026-07-15T10:00:00"), duration: 60, status: "Scheduled", type: "Video" },
  { id: "i2", candidateId: "c4", candidateName: "David Park", jobId: "j3", jobTitle: "ML Engineer", scheduledAt: new Date("2026-07-16T14:00:00"), date: new Date("2026-07-16T14:00:00"), duration: 90, status: "Scheduled", type: "AI" },
  { id: "i3", candidateId: "c10", candidateName: "Tom Bradley", jobId: "j1", jobTitle: "Senior Frontend Engineer", scheduledAt: new Date("2026-07-17T11:00:00"), date: new Date("2026-07-17T11:00:00"), duration: 60, status: "Scheduled", type: "Video" },
  { id: "i4", candidateId: "c8", candidateName: "Alex Rivera", jobId: "j7", jobTitle: "Backend Engineer", scheduledAt: new Date("2026-06-28T09:00:00"), date: new Date("2026-06-28T09:00:00"), duration: 60, status: "Completed", type: "On-site", score: 91 },
]

const sampleActivities: Activity[] = [
  { id: "a1", type: "application", candidateName: "Carlos Mendez", message: "applied for", timestamp: new Date("2026-07-12T14:30:00") },
  { id: "a2", type: "interview", candidateName: "Emily Chen", message: "scheduled interview for", timestamp: new Date("2026-07-12T11:00:00") },
  { id: "a3", type: "hire", candidateName: "Alex Rivera", message: "was hired for", timestamp: new Date("2026-07-01T09:00:00") },
  { id: "a4", type: "rejection", candidateName: "Priya Patel", message: "was not selected for", timestamp: new Date("2026-06-28T16:00:00") },
  { id: "a5", type: "offer", candidateName: "Sarah Kim", message: "received offer for", timestamp: new Date("2026-06-27T10:00:00") },
]

export const useStore = create<AppState>((set) => ({
  jobs: sampleJobs,
  candidates: sampleCandidates,
  interviews: sampleInterviews,
  activities: sampleActivities,
  addJob: (job) =>
    set((state) => ({
      jobs: [
        {
          ...job,
          id: `j${Date.now()}`,
          applicants: 0,
          createdAt: new Date(),
        },
        ...state.jobs,
      ],
    })),
  updateJobStatus: (id, status) =>
    set((state) => ({
      jobs: state.jobs.map((j) => (j.id === id ? { ...j, status } : j)),
    })),
  addCandidate: (candidate) =>
    set((state) => ({
      candidates: [
        {
          ...candidate,
          id: `c${Date.now()}`,
          stage: candidate.status,
          appliedAt: new Date(),
        },
        ...state.candidates,
      ],
    })),
  updateCandidateStatus: (id, status) =>
    set((state) => ({
      candidates: state.candidates.map((c) =>
        c.id === id ? { ...c, status, stage: status } : c
      ),
    })),
}))
