export type ScreeningWorkflowState =
  | 'IDLE'
  | 'LOADING_APPLICATIONS'
  | 'APPLICATION_SELECTED'
  | 'RESUME_MISSING'
  | 'UPLOADING_RESUME'
  | 'RESUME_READY'
  | 'REQUESTING_SCREENING'
  | 'WAITING_FOR_EXTRACTION'
  | 'SCREENING_PENDING'
  | 'SCREENING_RUNNING'
  | 'SCREENING_COMPLETED'
  | 'SCREENING_FAILED'
  | 'EXTRACTION_FAILED'
  | 'TIMED_OUT'
  | 'ERROR'

export const NON_TERMINAL_SCREENING_STATUSES = new Set(['PENDING', 'RUNNING'])
export const TERMINAL_SCREENING_STATUSES = new Set(['COMPLETED', 'FAILED'])

export const POLLING_INTERVAL_MS = 2000
export const MAX_POLLING_DURATION_MS = 120_000
export const EXTRACTION_RETRY_INTERVAL_MS = 2000
export const MAX_EXTRACTION_WAIT_MS = 120_000
