export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  REFRESH_REUSE_DETECTED: 'AUTH_REFRESH_REUSE_DETECTED',
  COMPANY_SELECTION_REQUIRED: 'AUTH_COMPANY_SELECTION_REQUIRED',
  MEMBERSHIP_INACTIVE: 'AUTH_MEMBERSHIP_INACTIVE',
  PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
  VERIFICATION_TOKEN_INVALID: 'AUTH_VERIFICATION_TOKEN_INVALID',
  VERIFICATION_TOKEN_EXPIRED: 'AUTH_VERIFICATION_TOKEN_EXPIRED',
  PASSWORD_POLICY_FAILED: 'AUTH_PASSWORD_POLICY_FAILED',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
  SESSION_STORE_UNAVAILABLE: 'AUTH_SESSION_STORE_UNAVAILABLE',
} as const;

export const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const REFRESH_TOKEN_BYTES = 48;
export const VERIFICATION_TOKEN_BYTES = 32;

export const DEFAULT_PERMISSIONS = [
  { code: 'company.read', name: 'Read company', resource: 'company', action: 'read' },
  { code: 'company.update', name: 'Update company', resource: 'company', action: 'update' },
  {
    code: 'company.manage_members',
    name: 'Manage company members',
    resource: 'company',
    action: 'manage_members',
  },
  { code: 'users.read', name: 'Read users', resource: 'users', action: 'read' },
  { code: 'users.invite', name: 'Invite users', resource: 'users', action: 'invite' },
  { code: 'users.update', name: 'Update users', resource: 'users', action: 'update' },
  { code: 'users.suspend', name: 'Suspend users', resource: 'users', action: 'suspend' },
  { code: 'roles.read', name: 'Read roles', resource: 'roles', action: 'read' },
  { code: 'roles.manage', name: 'Manage roles', resource: 'roles', action: 'manage' },
  { code: 'jobs.create', name: 'Create jobs', resource: 'jobs', action: 'create' },
  { code: 'jobs.read', name: 'Read jobs', resource: 'jobs', action: 'read' },
  { code: 'jobs.update', name: 'Update jobs', resource: 'jobs', action: 'update' },
  { code: 'jobs.publish', name: 'Publish jobs', resource: 'jobs', action: 'publish' },
  { code: 'jobs.close', name: 'Close jobs', resource: 'jobs', action: 'close' },
  { code: 'candidates.read', name: 'Read candidates', resource: 'candidates', action: 'read' },
  {
    code: 'candidates.create',
    name: 'Create candidates',
    resource: 'candidates',
    action: 'create',
  },
  {
    code: 'candidates.update',
    name: 'Update candidates',
    resource: 'candidates',
    action: 'update',
  },
  {
    code: 'candidates.archive',
    name: 'Archive/restore candidates',
    resource: 'candidates',
    action: 'archive',
  },
  {
    code: 'candidates.block',
    name: 'Block/unblock candidates',
    resource: 'candidates',
    action: 'block',
  },
  {
    code: 'candidates.merge',
    name: 'Merge candidates',
    resource: 'candidates',
    action: 'merge',
  },
  {
    code: 'candidates.view_sensitive',
    name: 'View sensitive candidate data',
    resource: 'candidates',
    action: 'view_sensitive',
  },
  {
    code: 'candidates.delete',
    name: 'Delete candidates',
    resource: 'candidates',
    action: 'delete',
  },
  {
    code: 'applications.read',
    name: 'Read applications',
    resource: 'applications',
    action: 'read',
  },
  {
    code: 'applications.move',
    name: 'Move applications',
    resource: 'applications',
    action: 'move',
  },
  {
    code: 'applications.override_ai',
    name: 'Override AI score',
    resource: 'applications',
    action: 'override_ai',
  },
  {
    code: 'interviews.create',
    name: 'Create interviews',
    resource: 'interviews',
    action: 'create',
  },
  { code: 'interviews.read', name: 'Read interviews', resource: 'interviews', action: 'read' },
  {
    code: 'interviews.update',
    name: 'Update interviews',
    resource: 'interviews',
    action: 'update',
  },
  {
    code: 'interviews.review',
    name: 'Review interviews',
    resource: 'interviews',
    action: 'review',
  },
  {
    code: 'interviews.reschedule',
    name: 'Reschedule interviews',
    resource: 'interviews',
    action: 'reschedule',
  },
  {
    code: 'interviews.cancel',
    name: 'Cancel interviews',
    resource: 'interviews',
    action: 'cancel',
  },
  {
    code: 'interviews.complete',
    name: 'Complete interviews',
    resource: 'interviews',
    action: 'complete',
  },
  {
    code: 'interviews.record_result',
    name: 'Record interview results',
    resource: 'interviews',
    action: 'record_result',
  },
  {
    code: 'interviews.manage_participants',
    name: 'Manage interview participants',
    resource: 'interviews',
    action: 'manage_participants',
  },
  { code: 'assessments.read', name: 'Read assessments', resource: 'assessments', action: 'read' },
  {
    code: 'assessments.create',
    name: 'Create assessments',
    resource: 'assessments',
    action: 'create',
  },
  {
    code: 'assessments.update',
    name: 'Update assessments',
    resource: 'assessments',
    action: 'update',
  },
  {
    code: 'assessments.publish',
    name: 'Publish assessments',
    resource: 'assessments',
    action: 'publish',
  },
  {
    code: 'assessments.assign',
    name: 'Assign assessments',
    resource: 'assessments',
    action: 'assign',
  },
  {
    code: 'assessments.review',
    name: 'Review assessment results',
    resource: 'assessments',
    action: 'review',
  },
  {
    code: 'notifications.send',
    name: 'Send notifications',
    resource: 'notifications',
    action: 'send',
  },
  {
    code: 'notifications.send_bulk',
    name: 'Send bulk notifications',
    resource: 'notifications',
    action: 'send_bulk',
  },
  { code: 'analytics.read', name: 'Read analytics', resource: 'analytics', action: 'read' },
  { code: 'reports.read', name: 'Read reports', resource: 'reports', action: 'read' },
  { code: 'reports.export', name: 'Export reports', resource: 'reports', action: 'export' },
  { code: 'settings.read', name: 'Read settings', resource: 'settings', action: 'read' },
  { code: 'settings.update', name: 'Update settings', resource: 'settings', action: 'update' },
  { code: 'audit.read', name: 'Read audit logs', resource: 'audit', action: 'read' },
] as const;

export const SYSTEM_ROLES = {
  PLATFORM_ADMIN: {
    code: 'PLATFORM_ADMIN',
    name: 'Platform Administrator',
    scope: 'PLATFORM' as const,
  },
  COMPANY_ADMIN: {
    code: 'COMPANY_ADMIN',
    name: 'Company Administrator',
    scope: 'COMPANY' as const,
  },
  HR_MANAGER: { code: 'HR_MANAGER', name: 'HR Manager', scope: 'COMPANY' as const },
  RECRUITER: { code: 'RECRUITER', name: 'Recruiter', scope: 'COMPANY' as const },
  HIRING_MANAGER: { code: 'HIRING_MANAGER', name: 'Hiring Manager', scope: 'COMPANY' as const },
  INTERVIEWER: { code: 'INTERVIEWER', name: 'Interviewer', scope: 'COMPANY' as const },
  VIEWER: { code: 'VIEWER', name: 'Viewer', scope: 'COMPANY' as const },
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  COMPANY_ADMIN: [
    'company.read',
    'company.update',
    'company.manage_members',
    'users.read',
    'users.invite',
    'users.update',
    'users.suspend',
    'roles.read',
    'roles.manage',
    'jobs.create',
    'jobs.read',
    'jobs.update',
    'jobs.publish',
    'jobs.close',
    'candidates.read',
    'candidates.create',
    'candidates.update',
    'candidates.archive',
    'candidates.block',
    'candidates.merge',
    'candidates.view_sensitive',
    'candidates.delete',
    'applications.read',
    'applications.move',
    'applications.override_ai',
    'interviews.create',
    'interviews.read',
    'interviews.update',
    'interviews.review',
    'interviews.reschedule',
    'interviews.cancel',
    'interviews.complete',
    'interviews.record_result',
    'interviews.manage_participants',
    'assessments.read',
    'assessments.create',
    'assessments.update',
    'assessments.publish',
    'assessments.assign',
    'assessments.review',
    'notifications.send',
    'notifications.send_bulk',
    'analytics.read',
    'reports.read',
    'reports.export',
    'settings.read',
    'settings.update',
    'audit.read',
  ],
  HR_MANAGER: [
    'company.read',
    'users.read',
    'users.invite',
    'roles.read',
    'jobs.create',
    'jobs.read',
    'jobs.update',
    'jobs.publish',
    'jobs.close',
    'candidates.read',
    'candidates.create',
    'candidates.update',
    'candidates.archive',
    'candidates.block',
    'candidates.view_sensitive',
    'applications.read',
    'applications.move',
    'interviews.create',
    'interviews.read',
    'interviews.update',
    'interviews.cancel',
    'interviews.reschedule',
    'interviews.complete',
    'interviews.record_result',
    'interviews.manage_participants',
    'interviews.review',
    'assessments.read',
    'assessments.create',
    'assessments.update',
    'assessments.publish',
    'assessments.assign',
    'assessments.review',
    'notifications.send',
    'notifications.send_bulk',
    'analytics.read',
    'reports.read',
    'reports.export',
    'settings.read',
  ],
  RECRUITER: [
    'company.read',
    'users.read',
    'jobs.create',
    'jobs.read',
    'jobs.update',
    'candidates.read',
    'candidates.create',
    'candidates.update',
    'candidates.archive',
    'applications.read',
    'applications.move',
    'interviews.create',
    'interviews.read',
    'interviews.update',
    'interviews.cancel',
    'interviews.reschedule',
    'interviews.complete',
    'interviews.record_result',
    'interviews.manage_participants',
    'assessments.read',
    'assessments.create',
    'assessments.update',
    'assessments.publish',
    'assessments.assign',
    'assessments.review',
    'notifications.send',
    'analytics.read',
    'reports.read',
  ],
  HIRING_MANAGER: [
    'company.read',
    'jobs.read',
    'jobs.update',
    'candidates.read',
    'applications.read',
    'interviews.read',
    'interviews.review',
    'assessments.read',
    'assessments.review',
    'analytics.read',
  ],
  INTERVIEWER: [
    'company.read',
    'interviews.read',
    'interviews.update',
    'interviews.record_result',
    'candidates.read',
    'applications.read',
  ],
  VIEWER: [
    'company.read',
    'users.read',
    'jobs.read',
    'candidates.read',
    'applications.read',
    'interviews.read',
    'assessments.read',
    'analytics.read',
    'reports.read',
  ],
};
